### ISSUE TITLE
Header links, on github help article pages, hide on mouse over

### ISSUE THREAD

**Issue by duianto** [Mottie/Octopatcher#4]
The link to the left of a header text, on github help article pages, disappear when the mouse moves to the left of the header text. This removes the ability to right click on the link, and copy the direct link to a header.

The issue can be observed on the page: https://help.github.com/articles/set-up-git/
On the heading: Setting up Git

When the mouse pointer is over the header text, then a link icon is shown to the left of the header text. But when the mouse pointer moves to the left of the header text, then the link disappears.

Disabling the octopatcher extension, and refreshing the page, brings back the expected behaviour, of the link remaining visible when the mouse pointer moves over it.

The issue doesn't occur on non github help article pages, like for example: https://github.com/Mottie/Octopatcher

System Info:
Octopatcher 1.1.0
Google Chrome 63.0.3239.108 (Official Build) (64-bit)
Windows 10 Version 1709 (OS Build 16299.125)

**Comment by Mottie** [comment]
Hi @duianto!

Thanks for letting me know! I'll have this patch fixed and updated ASAP.

**Comment by duianto** [comment]
It works now, thank you.
